# Generated by Django 4.2.3 on 2023-07-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('no_of_floors', models.IntegerField()),
                ('no_of_elevators', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('stoped', 'stoped'), ('up', 'up'), ('down', 'down')], default='stoped', max_length=10)),
                ('door_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=6)),
                ('working_status', models.CharField(choices=[('working', 'working'), ('under maintenance', 'under maintenance')], default='working', max_length=18)),
                ('current_floor', models.IntegerField(default=0)),
                ('elevator_no', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator', to='app.building')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing', max_length=9)),
                ('direction', models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4, null=True)),
                ('current_floor', models.IntegerField()),
                ('destination_floor', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.building')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.elevator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
