# Generated by Django 4.1.4 on 2023-07-27 04:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('no_of_floors', models.IntegerField()),
                ('no_of_elevators', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('up', 'up'), ('down', 'down')], default='available', max_length=10)),
                ('door_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=6)),
                ('is_working', models.BooleanField(default=True)),
                ('bulding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator', to='app.bulding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='app.elevator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4, null=True)),
                ('bulding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.bulding')),
                ('current_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.floor')),
                ('destination_floors', models.ManyToManyField(to='app.floor')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.elevator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
