# Generated by Django 4.1.4 on 2023-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='door_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=6),
        ),
    ]
