# Generated by Django 4.2.3 on 2023-07-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_elevator_elevator_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='elevator_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
