# Generated by Django 4.1.4 on 2023-07-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_elevator_door_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_floor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='app.floor'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='app.bulding'),
        ),
    ]
