# Generated by Django 4.1.4 on 2023-07-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_elevator_current_floor_alter_floor_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='elevator_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
