# Generated by Django 4.2.3 on 2023-07-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_request_building_alter_request_current_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.building'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='destination_floors',
        ),
        migrations.AddField(
            model_name='request',
            name='destination_floors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_requests', to='app.floor'),
        ),
    ]
