# Generated by Django 4.2.3 on 2023-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_request_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='current_floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
