# Generated by Django 4.2.3 on 2023-07-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_elevator_current_floor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='destination_floors',
            new_name='destination_floor',
        ),
    ]
