# Generated by Django 4.2.3 on 2023-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_elevator_is_working_elevator_working_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id_'),
        ),
    ]
